### ISSUE TITLE
Fatal error in postgres container

### ISSUE THREAD

**Issue by varex83** [NethermindEth/zksync-remix-plugin#190] opened 2024-09-16 11:06 UTC
We have a bunch of similar **fatal** errors running the postgres on both [zksync-remix-prod-svc](https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/zksync-remix-plugin-prod-ecs-cluster/services/zksync-remix-prod-svc?region=us-east-2) and [zksync-remix-plugin-dev-ecs-cluster](https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/zksync-remix-plugin-dev-ecs-cluster/services?region=us-east-2)

<img width="1526" alt="image" src="https://github.com/user-attachments/assets/af651678-390a-4646-b5c8-fd697901dbc6">

**Comment by ghost** [comment] 2024-09-17 11:56
The fatal errors are specifically originating from the `postgres ` container, not from the `reth` or `zkremix`.

![Image](https://github.com/user-attachments/assets/045bd82c-ca50-47be-b64f-ef2991ee6b4b)
![Image](https://github.com/user-attachments/assets/1f5a113b-bc6f-4a15-9783-83ee068f95b9)

**Comment by ghost** [comment] 2024-09-17 12:03
- Image URI: `postgres:12`;
- Image Digest: `sha256:da8d2778145448102c8ab478fdcebd43848d6f220ddb12d87329afbade3fb6e7`
- 
```
            "name": "postgres",
            "image": "postgres:12",
            "cpu": 0,
            "portMappings": [],
            "essential": true,
            "environment": [
                {
                    "name": "POSTGRES_USER",
                    "value": "postgres"
                },
                {
                    "name": "POSTGRES_HOST_AUTH_METHOD",
                    "value": "trust"
                }
            ],
```

**Comment by varex83** [comment] 2024-09-17 12:05
yes, can we check what can be wrong? I assume, it something misconfigured probably

**Comment by ghost** [comment] 2024-09-17 12:17
The task definition specifies the postgres user, so the issue might be coming from the application's database connection settings. We need to ensure that it's not hardcoded to use root or another invalid role. However, after reviewing the source code, I didn’t find any reference to the root user or other invalid postgres users.
https://hub.docker.com/layers/matterlabs/local-node/latest2.0/images/sha256-1ca19797ddc68806ad7fe7d007a898f6342548b98d53b12bf1e4b439dc80bcdb?context=explore
![Image](https://github.com/user-attachments/assets/a834a332-b948-46f4-be48-b69aae2bba56)

**Comment by ghost** [comment] 2024-09-18 10:51
As discussed with @varex83 during the call, he will follow up with the wider zkSync team to gather recent updates, which he confirmed might include changes related to the PostgreSQL setup.

**Comment by ghost** [comment] 2024-09-19 11:13
@varex83 Do you have any updates on that issue from your discussions with the wider team?

**Comment by ghost** [comment] 2024-09-19 13:19
Looks like the issue might be related to the health check command, which is likely running as root by default.

 The pg_isready command checks PostgreSQL readiness, but it needs to run with the postgres user, which we define with the -U postgres flag. By setting the correct user in the command, this should fix the error.

**Comment by ghost** [comment] 2024-09-19 14:09
Since the error is happening every 30 seconds, matching the interval of the health check, it’s likely that the health check itself is causing the `FATAL: role "root" does not exist error`.

**Comment by ghost** [comment] 2024-09-20 13:03
@varex83 The fix has been successfully deployed, and the services are now running without any issues. The error FATAL: role "root" does not exist is no longer appearing. You can view the logs here: [AWS ECS Logs](https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/zksync-remix-plugin-dev-ecs-cluster/services/zksync-remix-dev-svc/tasks/4cc8dde6f5184ad4b6c310a3023a7eb4/logs?region=us-east-2).

Please proceed with verification on your end. Once confirmed, I will merge the PR.

**Closed as completed** 2024-09-20 13:13 UTC
Labels: priority, devops
